import java.util.HashMap;
import java.util.Set;

public class HashMatique {
    // creating a HashMap for all songs with lyrics
    HashMap<String, String> lyricMap = new HashMap<String, String>();
    Set<String> keys = lyricMap.keySet();

    public String getLyric(String song) {
        lyricMap.put("Spice Up Your Life","La la la la la la laLa la la la la la la la la La la la la la la la When you're feelin' sad and lowWe will take you where you gotta go Smilin', dancin', everything is free All you need is positivity Colours of the world Spice up your life Every boy and every girl Spice up your life People of the world Spice up your life Aah Slam it to the left If you're havin a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha (uh uh) Go round Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha Hai Si Ja Hold tight La la la la la la la la la La la la la la la la La la la la la la la la la La la la la la la la Yellow man in Timbuktu Colour for both me and you Kung Fu Fighting Dancing Queen Tribal Spaceman And all that's in between Colours of the world Spice up your life Every boy and every girl Spice up your life People of the world Spice up your life Aah Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha Go round Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha Hai Si Ja Hold tight Flamenco Lambada But hip-hop is harder We moonwalk the foxtrot Then polka the salsa Shake it, shake it, shake it Haka Shake it, shake it, shake it Haka Arriba aha Colours of the world Spice up your life Every boy and every girl Spice up your life People of the world Spice up your life Aah Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha (uh uh) Go round Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha (uh uh) Hai Si Ja Hold tight Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha Go round Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha Hai Si Ja Hold tight"); 
        lyricMap.put("Truth Hurts", "Why men great 'til they gotta be great? Wooh I just took a DNA test, turns out I'm 100% that bitch Even when I'm crying crazy Yeah, I got boy problems, that's the human in me Bling bling, then I solve 'em, that's the goddess in me You coulda had a bad bitch, non-committal Help you with your career, just a little You're supposed to hold me down But you're holding me back And that's the sound of me not calling you back Why men great 'til they gotta be great? Don't text me, tell it straight to my face Best friend sat me down in the salon chair Shampoo press, get you out of my hair Fresh photos with the bomb lighting New man on the Minnesota Vikings Truth hurts, needed something more exciting Bom bom bi bom bi dum dum, ay You tried to break my heart Oh, that breaks my heart That you thought you ever had it No you ain't from the start Hey, I'm glad you're back with your bitch I mean who would wanna hide this? I will never ever ever ever ever be your side chick I put the sing in single Ain't worried 'bout a ring on my finger So you can tell your friends: Shoot your shot When you see 'em It's OK, he already in my DMs Why men great 'til they gotta be great? Don't text me, tell it straight to my face Best friend sat me down in the salon chair Shampoo press, get you out of my hair Fresh photos with the bomb lighting New man on the Minnesota Vikings Truth hurts, needed something more exciting Bom bom bi bom bi dum dum, ay I'ma hit you back in a minute I don't play tag, bitch I been it We don't fuck with lies We don't do goodbyes We just keep it pushing like aye, aye, aye I'ma hit you back in a minute I don't play tag, bitch I been it We don't fuck with lies We don't do goodbyes We just keep it pushing like aye, aye, aye Why men great 'til they gotta be great? Don't text me, tell it straight to my face Best friend sat me down in the salon chair Shampoo press, get you out of my hair Fresh photos with the bomb lighting New man on the Minnesota Vikings Truth hurts, needed something more exciting Bom bom bi bom bi dum dum ay");
        lyricMap.put("Dancing Queen", "Ooh You can dance You can jive Having the time of your life Ooh, see that girl Watch that scene Digging the dancing queen Friday night and the lights are low Looking out for a place to go Where they play the right music Getting in the swing You come to look for a king Anybody could be that guy Night is young and the music's high With a bit of rock music Everything is fine You're in the mood for a dance And when you get the chance You are the dancing queen Young and sweet Only seventeen Dancing queen Feel the beat from the tambourine, oh yeah You can dance You can jive Having the time of your life Ooh, see that girl Watch that scene Digging the dancing queen You're a teaser, you turn 'em on Leave 'em burning and then you're gone Looking out for another Anyone will do You're in the mood for a dance And when you get the chance You are the dancing queen Young and sweet Only seventeen Dancing queen Feel the beat from the tambourine, oh yeah You can dance You can jive Having the time of your life Ooh, see that girl Watch that scene Digging the dancing queen Digging the dancing queen");

        // keySet method
        for(String key : keys) {
            if (key == song) {
                System.out.println(lyricMap.get(key));
            }
        }
        return song;
    }

    public String getAll() {
        lyricMap.put("Spice Up Your Life","La la la la la la laLa la la la la la la la la La la la la la la la When you're feelin' sad and lowWe will take you where you gotta go Smilin', dancin', everything is free All you need is positivity Colours of the world Spice up your life Every boy and every girl Spice up your life People of the world Spice up your life Aah Slam it to the left If you're havin a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha (uh uh) Go round Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha Hai Si Ja Hold tight La la la la la la la la la La la la la la la la La la la la la la la la la La la la la la la la Yellow man in Timbuktu Colour for both me and you Kung Fu Fighting Dancing Queen Tribal Spaceman And all that's in between Colours of the world Spice up your life Every boy and every girl Spice up your life People of the world Spice up your life Aah Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha Go round Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha Hai Si Ja Hold tight Flamenco Lambada But hip-hop is harder We moonwalk the foxtrot Then polka the salsa Shake it, shake it, shake it Haka Shake it, shake it, shake it Haka Arriba aha Colours of the world Spice up your life Every boy and every girl Spice up your life People of the world Spice up your life Aah Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha (uh uh) Go round Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha (uh uh) Hai Si Ja Hold tight Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha Go round Slam it to the left If you're havin' a good time Shake it to the right If ya know that you feel fine Chicas to the front Ha ha Hai Si Ja Hold tight"); 
        lyricMap.put("Truth Hurts", "Why men great 'til they gotta be great? Wooh I just took a DNA test, turns out I'm 100% that bitch Even when I'm crying crazy Yeah, I got boy problems, that's the human in me Bling bling, then I solve 'em, that's the goddess in me You coulda had a bad bitch, non-committal Help you with your career, just a little You're supposed to hold me down But you're holding me back And that's the sound of me not calling you back Why men great 'til they gotta be great? Don't text me, tell it straight to my face Best friend sat me down in the salon chair Shampoo press, get you out of my hair Fresh photos with the bomb lighting New man on the Minnesota Vikings Truth hurts, needed something more exciting Bom bom bi bom bi dum dum, ay You tried to break my heart Oh, that breaks my heart That you thought you ever had it No you ain't from the start Hey, I'm glad you're back with your bitch I mean who would wanna hide this? I will never ever ever ever ever be your side chick I put the sing in single Ain't worried 'bout a ring on my finger So you can tell your friends: Shoot your shot When you see 'em It's OK, he already in my DMs Why men great 'til they gotta be great? Don't text me, tell it straight to my face Best friend sat me down in the salon chair Shampoo press, get you out of my hair Fresh photos with the bomb lighting New man on the Minnesota Vikings Truth hurts, needed something more exciting Bom bom bi bom bi dum dum, ay I'ma hit you back in a minute I don't play tag, bitch I been it We don't fuck with lies We don't do goodbyes We just keep it pushing like aye, aye, aye I'ma hit you back in a minute I don't play tag, bitch I been it We don't fuck with lies We don't do goodbyes We just keep it pushing like aye, aye, aye Why men great 'til they gotta be great? Don't text me, tell it straight to my face Best friend sat me down in the salon chair Shampoo press, get you out of my hair Fresh photos with the bomb lighting New man on the Minnesota Vikings Truth hurts, needed something more exciting Bom bom bi bom bi dum dum ay");
        lyricMap.put("Dancing Queen", "Ooh You can dance You can jive Having the time of your life Ooh, see that girl Watch that scene Digging the dancing queen Friday night and the lights are low Looking out for a place to go Where they play the right music Getting in the swing You come to look for a king Anybody could be that guy Night is young and the music's high With a bit of rock music Everything is fine You're in the mood for a dance And when you get the chance You are the dancing queen Young and sweet Only seventeen Dancing queen Feel the beat from the tambourine, oh yeah You can dance You can jive Having the time of your life Ooh, see that girl Watch that scene Digging the dancing queen You're a teaser, you turn 'em on Leave 'em burning and then you're gone Looking out for another Anyone will do You're in the mood for a dance And when you get the chance You are the dancing queen Young and sweet Only seventeen Dancing queen Feel the beat from the tambourine, oh yeah You can dance You can jive Having the time of your life Ooh, see that girl Watch that scene Digging the dancing queen Digging the dancing queen");
        // looping through all songs and to get all lyrics
        for(String key : keys) {
                System.out.println(key + " : " + lyricMap.get(key));
        }
        // returning a blank string if nothing was returned in the for loop
        String songs = "";
        return songs;
    }
}
